services:
  - type: web
    name: whatsapp-backend
    env: python
    runtime: python-3.11.9
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
